In [1]:
import numpy as np

In [2]:
arr = [0, 1, 2, 3, 4, 5, 6, 7]
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7]


In [3]:
print(type(arr))

<class 'list'>


In [4]:
array = np.array(arr)
print(array)

[0 1 2 3 4 5 6 7]


In [5]:
print(type(array))

<class 'numpy.ndarray'>


In [6]:
print(array.shape)

(8,)


In [7]:
print(array.dtype)

int32


In [8]:
print(array.ndim)

1


In [9]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
print(type(array_2d))

<class 'numpy.ndarray'>


In [11]:
print(array_2d.shape)

(2, 3)


In [12]:
print(array_2d.dtype)

int32


In [13]:
print(array_2d.ndim)

2


In [14]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],
                     [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(array_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
print(type(array_2d))

<class 'numpy.ndarray'>


In [16]:
print(array_3d.shape)

(4, 2, 3)


In [17]:
print(array_3d.ndim)

3


In [18]:
print(np.empty(2, dtype=int))

[1065353216 1065353216]


In [19]:
print(np.empty([3, 3], dtype=int))

[[1768714611 1633641844 1768911989]
 [2019910766 1936287839 2037542772]
 [     12639    5177415    5439566]]


In [20]:
print(np.zeros([3, 3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones([5, 3], dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
print(np.full([3, 35], fill_value=5))

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


In [23]:
print(np.random.random([5, 5]))

[[0.50796053 0.23187754 0.58224056 0.82884974 0.13026071]
 [0.92637785 0.63817865 0.90314261 0.67120317 0.58350273]
 [0.54765231 0.21128535 0.11366684 0.31486732 0.07856374]
 [0.29169191 0.78870284 0.48447325 0.54165392 0.5553184 ]
 [0.38943152 0.90574222 0.86341411 0.40743402 0.17269555]]


In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[8, 7, 6, 5], [4, 3, 2, 1]])

In [25]:
print(a + b)

[[9 9 9 9]
 [9 9 9 9]]


In [26]:
print(a - b)

[[-7 -5 -3 -1]
 [ 1  3  5  7]]


In [27]:
print(a * b)

[[ 8 14 18 20]
 [20 18 14  8]]


In [28]:
print(a / b)

[[0.125      0.28571429 0.5        0.8       ]
 [1.25       2.         3.5        8.        ]]


In [29]:
print(a // b)

[[0 0 0 0]
 [1 2 3 8]]


In [30]:
print(a % b)

[[1 2 3 4]
 [1 0 1 0]]


In [31]:
print(10 / a)

[[10.          5.          3.33333333  2.5       ]
 [ 2.          1.66666667  1.42857143  1.25      ]]


In [32]:
print(b ** 2)

[[64 49 36 25]
 [16  9  4  1]]


In [33]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
a[0]

array([1, 2, 3, 4])

In [35]:
a[1]

array([5, 6, 7, 8])

In [36]:
a[0, 2] # a[0][2]

3

In [37]:
a[1, 3]

8

In [38]:
a[0, :4]

array([1, 2, 3, 4])

In [39]:
a[1, 1:3]

array([6, 7])

In [40]:
a[:1, 2:]

array([[3, 4]])

In [41]:
print(b)

[[8 7 6 5]
 [4 3 2 1]]


In [42]:
b[[0, 0, 1, 0, 1], [0, 2, 3, 3, 1]]

array([8, 6, 1, 5, 3])

In [43]:
b[b>5]

array([8, 7, 6])

In [44]:
a.sum()

36

In [45]:
a.max()

8

In [46]:
a.min()

1

In [47]:
a.mean()

4.5

In [48]:
a.mean(dtype=int) # round(a.mean())

4

In [49]:
a.std()

2.29128784747792

In [50]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [51]:
np.corrcoef(a, b)

array([[ 1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1.]])

In [58]:
assert 1 == 1.0